<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHvXc0Co\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHvXc0Co/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHvXc0Co.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHvXc0Co\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHvXc0Co\App_KernelDevDebugContainer([
    'container.build_hash' => 'HvXc0Co',
    'container.build_id' => '8041d22f',
    'container.build_time' => 1722457532,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHvXc0Co');
