<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\MainController::home'], [], [['text', '/']], [], [], []],
    'contact_us' => [[], ['_controller' => 'App\\Controller\\MainController::contacts'], [], [['text', '/nous-contacter']], [], [], []],
    'see_photos' => [[], ['_controller' => 'App\\Controller\\MainController::gallerie'], [], [['text', '/voir-les-photos']], [], [], []],
    'when_can_i_book' => [[], ['_controller' => 'App\\Controller\\MainController::disponibilites'], [], [['text', '/quand-sommes-nous-dispo']], [], [], []],
    'learn_more' => [[], ['_controller' => 'App\\Controller\\MainController::enSavoirPlus'], [], [['text', '/en-apprendre-plus']], [], [], []],
    'App\Controller\MainController::home' => [[], ['_controller' => 'App\\Controller\\MainController::home'], [], [['text', '/']], [], [], []],
    'App\Controller\MainController::contacts' => [[], ['_controller' => 'App\\Controller\\MainController::contacts'], [], [['text', '/nous-contacter']], [], [], []],
    'App\Controller\MainController::gallerie' => [[], ['_controller' => 'App\\Controller\\MainController::gallerie'], [], [['text', '/voir-les-photos']], [], [], []],
    'App\Controller\MainController::disponibilites' => [[], ['_controller' => 'App\\Controller\\MainController::disponibilites'], [], [['text', '/quand-sommes-nous-dispo']], [], [], []],
    'App\Controller\MainController::enSavoirPlus' => [[], ['_controller' => 'App\\Controller\\MainController::enSavoirPlus'], [], [['text', '/en-apprendre-plus']], [], [], []],
];
